### ISSUE TITLE
Upcoming and past shifts are not sorted chronologically

### ISSUE THREAD

**Issue by benajmin** [uwcrt/Real-Magic-Scheduler-update#5]
**Describe the bug**
On responder pages upcoming and past shifts are sorted by creation time.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create various shifts with a single responder on them, ensuring shifts are not created in chronological order
2. Navigate to responder's user page
3. Notice shifts are sorted by creation time instead of by start time

**Expected behaviour**
Shifts should be sorted by start time

**Screenshots**
<img width="3176" alt="image" src="https://user-images.githubusercontent.com/7366878/81016602-c13f1c80-8e2e-11ea-977a-7a408e63886d.png">

<img width="247" alt="image" src="https://user-images.githubusercontent.com/7366878/81016571-b4bac400-8e2e-11ea-9729-44af0870853f.png">

**Comment by timothy-zhang** [comment]
Dang QA and bug hunting
